using DotNext;
using DotNext.Net.Cluster.Consensus.Raft;

namespace RaftNode;

internal sealed class DataModifier : BackgroundService
{
    private readonly IRaftCluster cluster;
    private readonly ISupplier<BigStruct> valueProvider;

    public DataModifier(IRaftCluster cluster, ISupplier<BigStruct> provider)
    {
        this.cluster = cluster;
        valueProvider = provider;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        bool resuming = true;
        while (!stoppingToken.IsCancellationRequested)
        {
            var leadershipToken = cluster.LeadershipToken;
            if (!leadershipToken.IsCancellationRequested)
            {
                var oldValue = valueProvider.Invoke().Field1;
                if (resuming)
                    Console.WriteLine("Saving value {0} generated by the leader node", oldValue + 1);
                resuming = false;

                var source = CancellationTokenSource.CreateLinkedTokenSource(stoppingToken, leadershipToken);
                var linkedToken = source.Token;
                try
                {
                    var tasks = new List<Task<bool>>(16);
                    for (int i = 1; i <= 16; i++)
                    {
                        var entry = new BigLogEntry { Content = new BigStruct() { Field1 = oldValue + i }, Term = cluster.Term };
                        tasks.Add(cluster.ReplicateAsync(entry, linkedToken));
                    }

                    var responses = await Task.WhenAll(tasks);
                    if (responses.Contains(false))
                        Console.WriteLine($"failed to replicate {responses.Count(r => !r)} entries");
                }
                catch (Exception e)
                {
                    Console.WriteLine("Unexpected error {0}", e);
                    resuming = true;
                }
                finally
                {
                    source?.Dispose();
                }
            }
            else
                resuming = true;
        }
    }
}